apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-frontend
spec:
  destination:
    namespace: user1-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/mneukum/gitops-openshift-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
